
# Shellfish Resilience to Prehistoric Human consumption in the southern Red Sea

This compendium contains the code and data to reproduce some of the figures and statstical data discussed in the article:

`Hausmann, N., Meredith-Williams, M., and Laurie, E. (in review) Shellfish Resilience to Prehistoric Human consumption in the southern Red Sea. Quaternary international`

##  How to run on Code Ocean
I suggest to run the code by downloading the entire capsule and executing the steps on your own PC. This wil require some changing of the paths, but should be too difficult. You can also run the individual files on CodeOcean by opening a n RStudio session using the button on the right above the timeline. If you don’t want to run anything yourself, or if there is an error, or if you have a free account and your time is up, you can see the finished figures in the “Figures and supplementary Material” folder and the individual files that explain how to create them in the “Walkthrough” folder.

##Walkthroughs
This capsule was created in a rush and by an R enthusiast, who still has lots to learn. Some of the solution that I have found are not straightforward and not the easiest way of doing things. They shall only explain how I ended up doing the things, that I did for the paper, and to show what worked for me.

## Farasan Shell Database
Finally this capsule is a means to make the Farasan Shell database more accessible It is a rough format that needs tidying up, but there are lots of datasets in here, which remain unstudied. Feel free to have a look around and please get in touch if you have any questions or ideas.

Niklas (niklas@palaeo.eu)