
SW$Speciesname <- lapply(SW$Species,as.character) 




SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Strombus.fasciatus.......Born.1778..Lineated.Conch", "Conomurex fasciatus")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Strombus.fasciatus..............Born.1778.", "Conomurex fasciatus")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Chicoreus.ramosus......Linnaeus.1758.", "Chicoreus species")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Chicoreus.virgineus..Röding.1798.", "Chicoreus species")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Arca.avellana..Lamarck.1819.", "Arca species")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Beguina.gubernaculum..Reeve.1843.", "Beguina gubernaculum")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Chama.reflexa..Reeve.1846.", "Chama pacifica")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Modiolus.auriculatus..Krauss.1848.", "Modiolus auriculatus")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Spondylus.marisrubri.......................Röding.1798..................................Spiny.or.Thorny.Oyster", "Spondylus spinosus")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Strombus.tricornis..Lightfoot.1786.", "Strombus tricornis")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Strombus..tricornis..tricornis.......Lightfoot.1786..Mouth", "Strombus tricornis")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Arca.ventricosa..Lamarck.1819.", "Arca ventricosa")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Pleuroploca.trapezium..Linnaeus.1758.", "Pleuroploca trapezium")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Pleuroploca.trapezium", "Pleuroploca trapezium")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Volema.paradisiaca.nodosa.Lamarck.1822.", "Volema paradisiaca nodosa")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Trochus.dentatus..Forsk?.l.1775..Knobbed.Top.Shell", "Trochus dentatus")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Plicatula.plicata..Linnaeus.1767.", "Plicatula plicata")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Arca.Species..............................Ark.Shell", "Arca species")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Arca.Species.to.be.revisited.when.speciemen.Species.available", "Arca species")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Chicoreus.virgineus..R?.ding.1798.", "Chicoreus species")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Strombus..tricornis..tricornis..Lightfoot.1786.", "Strombus tricornis")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Tibia.insulaechorab.curta...............Sowerby.1842.", "Tibia insulaechorab")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Chicoreus.ramosus...Linnaeus.1758.", "Chicoreus species")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Chicoreus.ramosus..Linnaeus.1758.", "Chicoreus species")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Chicoreus.ramosus......Linnaeus.1758..Mouth", "Chicoreus species")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Chicoreus.ramosus......Linnaeus.1758..Siphon", "Chicoreus species")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Chama.reflexa..Reeve.1846......Jewel.Box", "Chama pacifica")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Pinctada.Species", "Pinctada species")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Ostrea.Species", "Ostrea species")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Rapana.rapiformis........Born.1778.", "Rapana rapiformis")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Chlamys.townsendi..Sowerby.1895.............................................Townsends.Scallop", "Chlamys townsendi")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Anadara.antiquata..Linnaeus.1758.", "Anadara antiquata")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Atactodea.Species", "Atactodea species")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Volema.paradisiaca.nodosa..Lamarck.1822.", "Volema paradisiaca")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Trapezium.sublaevigatum..Lamarck.1819.", "Trapezium sublaevigatum")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Plicatula.plicata..Linnaeus.1758..Kittens.Paw", "Plicatula plicata")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Conus.arenatus.aequipunctatus..............Hwass.1792.", "Conus arenatus")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Beguina.gubernaculum.....................................Reeve.1843..................................................Rudder.Cardita", "Begunia gubernaculum")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Modiolus.auriculatus.....Krauss.1848.", "Modiolus auriculatus")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Ostrea.sp...................................Oyster", "Ostrea species")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Chicoreus.Species", "Chicoreus species ")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Tridacna.maxima..Röding.1798.", "Tridacna maxima")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Conus.Species", "Conus species")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Anadara.antiquata.....................Linnaeus.1758.", "Anadara antiquata")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Chama.Species", "Chama species")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Trochus.dentatus..Forskål.1775..Knobbed.Top.Shell", "Trochus dentatus")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Trochus.dentatus..Forskå1.1775..Knobbed.Top.Shell", "Trochus dentatus")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Trochus.dentatus..Forskål.1775..also.Tectus.dentatus..Forskål.1775..Knobbed.Top.Shell", "Trochus dentatus")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Trochus.dentatus..Forskål.1775..Knobbed.Topshell.Red.Sea.Topshell", "Trochus dentatus")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Ostreiodea.Species", "Ostreidea species")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Strombus..tricornis..tricornis.......Lightfoot.1786.", "Strombus tricornis")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Arca.ventricosa.......................Lamarck.1819................................Ar", "Arca ventricosa")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Pleuroploca.trapezium..Linnaeus.1758..Trapezoid.Horse.Conch", "Pleuroploca trapezium")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Tridacna.maxima..Röding.1798..", "Tridacna maxima")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Tridacna.maxima..Röding.1798.", "Tridacna maxima")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Nerita.Species", "Nerita species")
SW$Speciesname <- replace(SW$Speciesname, SW$Species=="Arca.ventricosa.......................Lamarck.1819................................Ark.Shell", "Arca ventricosa")
# SW$Speciesname <- replace(SW$Speciesname, SW$Species=="", " ") ADD MORE IF YOU WANT


